name: Publish package

on:
  push:
    tags: ["v*"]

permissions: {}

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false # never abort a half-finished release

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@10c66d66e558b37df92e2a8ec5321218a6547b04 # main
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      generate: true
